// <auto-generated />
using HardwareManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HardwareManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705000001_Phase521_RestoreManagement")]
    partial class Phase521_RestoreManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left minimal.
            // Full model state is captured in ApplicationDbContextModelSnapshot.cs.
            // This stub is sufficient for dotnet ef database update to discover and apply this migration.
        }
    }
}
