# -*- coding: utf-8 -*-
"""Phase UM-1 — generates the three professional DOCX manuals."""
import os
from docx_engine import Manual

OUT = os.path.join(os.path.dirname(__file__), "..")

# =====================================================================
# MANUAL 1 — SUPERADMIN (INTERNAL)
# =====================================================================
SUPERADMIN = [
    {"heading": "Introduction", "blocks": [
        ("purpose", "This manual is the operational reference for the System Owner who administers the Hardware Supply POS platform. It explains how the multi-tenant Software-as-a-Service (SaaS) system is structured and how to provision, operate, and support customer tenants."),
        ("p", "Hardware Supply POS is a cloud point-of-sale and inventory platform for hardware and construction-supply businesses. A single deployment serves many independent customers (\u201ctenants\u201d), each with isolated data, users, branches, products, and reports."),
        ("warning", "This document is for internal use by the platform owner and authorized operators only. It contains administrative procedures that must never be shared with end customers."),
        ("bullets", [
            "SuperAdmin sign-in URL: /Account/Login",
            "SuperAdmin console: SaaS Management menu (Dashboard, Tenants, Subscription Plans, Global Audit Trail)",
            "Default platform account: superadmin (rotate the password before go-live).",
        ]),
    ]},
    {"heading": "System Architecture", "blocks": [
        ("purpose", "Understand how platform data and tenant operational data are separated so you can provision and troubleshoot tenants safely."),
        ("h2", "Two database layers"),
        ("bullets", [
            "Shared platform database \u2014 stores identity (users, roles, permissions), tenant metadata, subscription plans, and the global audit trail. All tenants that run in Shared mode also keep their operational data here, isolated by a TenantId column.",
            "Dedicated tenant database \u2014 an optional, per-tenant operational database (its own catalog on the SQL Server) used by larger customers. It holds that tenant\u2019s products, inventory, sales, suppliers, customers, and related records.",
        ]),
        ("h2", "Runtime routing"),
        ("p", "On each request the platform resolves the signed-in user\u2019s tenant, then decides whether to read and write operational data in the shared database or in that tenant\u2019s dedicated database. The decision is driven by the tenant\u2019s database flags (described in the Routing and Provisioning chapters)."),
        ("note", "Identity and tenant metadata always live in the shared database, even for tenants that use a dedicated operational database. This keeps sign-in and platform administration consistent for every tenant."),
    ]},
    {"heading": "SaaS Overview", "blocks": [
        ("purpose", "Get a platform-wide picture of tenants, branches, users, and product usage from a single screen."),
        ("steps", [
            "Sign in with the SuperAdmin account.",
            "You arrive on the SuperAdmin Dashboard automatically.",
            "Review the KPI cards (Total Tenants, Active Branches, Active Users, Total Products).",
            "Use the Tenant Overview table to see each tenant\u2019s plan, status, and usage against its limits.",
        ]),
        ("fig", "super_dashboard", "SuperAdmin Dashboard \u2014 platform-wide tenant, branch, user, and product overview."),
        ("expected", "The dashboard shows live totals and a per-tenant usage table with quick links to manage or view each tenant."),
    ]},
    {"heading": "Tenant Management", "blocks": [
        ("purpose", "Find, review, and manage every customer tenant on the platform."),
        ("steps", [
            "Open SaaS Management \u2192 Tenants.",
            "Use the list to review each tenant\u2019s name, code, plan, status, and usage.",
            "Select a tenant row to open its details, or use New Tenant to onboard a customer.",
        ]),
        ("fig", "super_tenants", "Tenants list \u2014 all customer tenants with plan, status, and usage limits."),
        ("note", "A tenant can be Active, Suspended, or otherwise restricted. Suspended tenants cannot sign in; their data is retained."),
    ]},
    {"heading": "Subscription Plans", "blocks": [
        ("purpose", "Define the commercial tiers (limits on branches, users, and products) that tenants are assigned to."),
        ("steps", [
            "Open SaaS Management \u2192 Subscription Plans.",
            "Review existing plans and their limits.",
            "Create or edit a plan to set maximum branches, users, and products.",
            "Assign the plan to a tenant from the tenant\u2019s record.",
        ]),
        ("fig", "super_plans", "Subscription Plans \u2014 commercial tiers and their resource limits."),
        ("expected", "Each tenant\u2019s usage is measured against the limits of its assigned plan, shown on the dashboard and tenant list."),
    ]},
    {"heading": "Tenant Creation", "blocks": [
        ("purpose", "Onboard a new customer by creating a tenant and its first administrator."),
        ("steps", [
            "Open SaaS Management \u2192 Tenants and click New Tenant.",
            "Enter the business name and a short unique tenant code.",
            "Choose the subscription plan and set the limits (branches, users, products).",
            "Provide the first Tenant Administrator\u2019s name, username, and email.",
            "Save. The tenant starts in Shared database mode by default.",
        ]),
        ("fig", "super_create_tenant", "Create Tenant \u2014 business details, plan, limits, and the first administrator account."),
        ("tip", "Use a short, stable tenant code (for example HSC). It is used internally and should not be changed after go-live."),
        ("expected", "A new Active tenant appears in the list with one Tenant Administrator who can sign in immediately."),
    ]},
    {"heading": "Tenant Administration", "blocks": [
        ("purpose", "Manage an individual tenant: review usage, manage its users, suspend or reactivate it, and reset administrator passwords."),
        ("steps", [
            "Open Tenants and select the tenant to open its Details page.",
            "Review usage, plan, and the tenant\u2019s users.",
            "Use Suspend to block access (data is retained) or Reactivate to restore it.",
            "Use Reset Password to issue a new password to a tenant user when required.",
        ]),
        ("fig", "super_tenant_details", "Tenant Details \u2014 usage, users, status controls, and the dedicated-database panel."),
        ("warning", "Suspending a tenant immediately prevents all of that tenant\u2019s users from signing in. Confirm with the account owner before suspending a live customer."),
    ]},
    {"heading": "User Administration", "blocks": [
        ("purpose", "Manage platform and tenant user accounts, including activation state and roles."),
        ("steps", [
            "Open the Users area.",
            "Locate a user by name, username, or tenant.",
            "Activate or deactivate accounts and confirm role assignments.",
        ]),
        ("fig", "super_users", "User administration \u2014 accounts, roles, and activation state."),
        ("note", "Deactivated users keep their history but cannot sign in. Prefer deactivation over deletion to preserve the audit trail."),
    ]},
    {"heading": "Permissions", "blocks": [
        ("purpose", "Control what each role can see and do through module-level permissions."),
        ("steps", [
            "Open the Roles / Role Permissions area.",
            "Select a role (for example TenantAdmin, BranchManager, Cashier).",
            "Grant or revoke access per module (POS, Inventory, Reports, and so on).",
            "Save. Changes apply the next time affected users load a page.",
        ]),
        ("fig", "super_roles", "Roles and module permissions \u2014 access control per role."),
        ("warning", "The Cashier role is intentionally limited. Grant only the modules a cashier needs (POS, Sales) to keep least-privilege access."),
    ]},
    {"heading": "Dedicated Database Provisioning", "blocks": [
        ("purpose", "Create a dedicated operational database for a tenant that has outgrown shared mode."),
        ("steps", [
            "Open the tenant\u2019s Details page and locate the dedicated-database panel.",
            "Switch the tenant\u2019s database mode to Dedicated.",
            "Click Provision. The platform creates the tenant\u2019s database, applies the operational schema (migrations), and seeds minimal required data.",
            "Click Test Connection to confirm the new database is reachable.",
        ]),
        ("fig", "super_tenant_details", "Dedicated-database panel \u2014 provisioning, connection test, migration, and routing controls."),
        ("note", "Provisioning only creates and prepares the database. It does NOT move existing data or send traffic to it yet \u2014 those are separate, deliberate steps (Migration and Routing)."),
        ("warning", "Provisioning is a one-time setup per tenant. If a dedicated database already exists for the tenant, the platform will not overwrite it."),
    ]},
    {"heading": "Database Migration", "blocks": [
        ("purpose", "Copy the tenant\u2019s existing operational data from the shared database into its newly provisioned dedicated database."),
        ("steps", [
            "Confirm the tenant is provisioned and the connection test passes.",
            "On the tenant\u2019s Details page, click Migrate Data.",
            "Wait for the migration to complete and review the reported row counts.",
            "Open Database Diagnostics to verify record counts match expectations.",
        ]),
        ("fig", "super_db_diagnostics", "Database Diagnostics \u2014 used to confirm migrated record counts and database health."),
        ("warning", "Run migration during a quiet period. Avoid letting the tenant create new sales while data is being copied to prevent split records."),
    ]},
    {"heading": "Routing Enable / Disable", "blocks": [
        ("purpose", "Switch a tenant\u2019s live operational traffic to (or away from) its dedicated database."),
        ("steps", [
            "Confirm provisioning and migration are complete and verified.",
            "On the tenant\u2019s Details page, click Enable Routing.",
            "Ask the tenant to sign in and confirm their data is present and correct.",
            "To revert, click Disable Routing (see Rollback Procedure).",
        ]),
        ("fig", "super_tenant_details", "Routing controls \u2014 enable or disable dedicated-database routing for the tenant."),
        ("note", "Routing only takes effect when every required flag is satisfied: mode is Dedicated, the database is provisioned, data is migrated, routing is enabled, and a connection string is resolved."),
    ]},
    {"heading": "Rollback Procedure", "blocks": [
        ("purpose", "Safely return a tenant to the shared database if an issue is found after routing is enabled."),
        ("steps", [
            "Open the tenant\u2019s Details page.",
            "Click Disable Routing. The tenant immediately resumes using the shared database.",
            "Confirm the tenant can sign in and see their pre-migration data.",
            "Investigate the dedicated database issue before attempting routing again.",
        ]),
        ("warning", "Rollback is non-destructive: disabling routing reverts the tenant to the shared database and the dedicated database is retained. Data created in the dedicated database while routed will not appear in the shared database after rollback \u2014 reconcile before re-enabling."),
        ("tip", "Because rollback is instant and safe, prefer enabling routing early in the day so you have a full business day to validate and, if needed, roll back."),
    ]},
    {"heading": "Diagnostics Page", "blocks": [
        ("purpose", "Inspect a tenant\u2019s database mode, routing state, connectivity, and record counts in one place."),
        ("steps", [
            "Open the tenant\u2019s Details page and click Database Info / Diagnostics.",
            "Review the active mode, routing flags, and connection status.",
            "Compare record counts against the shared database after a migration.",
        ]),
        ("fig", "super_db_diagnostics", "Database Diagnostics \u2014 mode, routing flags, connectivity, and record counts."),
        ("note", "Connection strings shown here are masked: only the server and database name are displayed and credentials are never exposed."),
    ]},
    {"heading": "Audit Monitoring", "blocks": [
        ("purpose", "Review who did what across the platform for security and support."),
        ("steps", [
            "Open SaaS Management \u2192 Global Audit Trail.",
            "Filter by user, action, module, or date range.",
            "Open an entry to see the details of the recorded change.",
        ]),
        ("fig", "super_audit", "Global Audit Trail \u2014 platform-wide record of user actions."),
        ("tip", "Use the audit trail first when investigating a support ticket \u2014 it usually shows exactly which action and user caused the reported state."),
    ]},
    {"heading": "Backup Procedures", "blocks": [
        ("purpose", "Protect both platform and tenant data, plus uploaded files, with regular backups."),
        ("bullets", [
            "Shared platform database \u2014 back up on a fixed schedule; it contains identity, tenant metadata, plans, audit, and all Shared-mode tenant data.",
            "Each dedicated tenant database \u2014 back up on the same schedule; one catalog per dedicated tenant.",
            "Uploaded files \u2014 back up the logos folder under wwwroot/uploads/logos/ (tenant logos are stored on the filesystem, not in the database).",
        ]),
        ("steps", [
            "Schedule full backups of the shared database and every dedicated database.",
            "Include the wwwroot/uploads/logos/ directory in the file backup job.",
            "Store backups off the application server and verify them regularly.",
        ]),
        ("note", "Refer to the internal Backup and Restore Guide for SQL Server commands and retention recommendations."),
    ]},
    {"heading": "Restore Procedures", "blocks": [
        ("purpose", "Recover platform or tenant data after loss or corruption."),
        ("steps", [
            "Identify the affected scope (shared database, a single dedicated database, or uploaded files).",
            "Restore the most recent verified backup for that scope.",
            "Restore the matching logos folder if files were affected.",
            "Run Database Diagnostics for affected tenants to confirm record counts and connectivity.",
        ]),
        ("warning", "Restoring the shared database affects every Shared-mode tenant. Schedule a maintenance window and notify customers before a platform-wide restore."),
    ]},
    {"heading": "QA Runner Usage", "blocks": [
        ("purpose", "Validate the tenant lifecycle (provision \u2192 migrate \u2192 route \u2192 operate) automatically before and after releases."),
        ("steps", [
            "Stop the running web application.",
            "From the project folder run the end-to-end QA runner with the appropriate flag (for example: dotnet run -- --qa-phase50d2).",
            "Watch the console for the pass/fail summary and review created QA_ records.",
            "Use the runner\u2019s cleanup option to remove QA_ test data when finished.",
        ]),
        ("note", "QA runners are Development-only utilities. They never start the web server and they tag all test data with a QA_ prefix so it is easy to identify and remove."),
        ("warning", "Never run QA runners against a production database."),
    ]},
    {"heading": "Troubleshooting", "blocks": [
        ("purpose", "Resolve the most common operational issues quickly."),
        ("bullets", [
            "Tenant cannot sign in \u2014 confirm the tenant is Active (not Suspended) and the user account is active.",
            "Routing has no effect \u2014 verify all flags: Dedicated mode, Provisioned, Data migrated, Routing enabled, and a resolvable connection string.",
            "Migration row counts look wrong \u2014 re-run Database Diagnostics; ensure no new sales were created mid-migration.",
            "Logo not displaying \u2014 confirm the file exists under wwwroot/uploads/logos/ and is within the 2 MB size limit.",
            "Page returns Not Found \u2014 navigate using the in-app menus; deep links require an explicit page action.",
        ]),
        ("tip", "Start every investigation with the Global Audit Trail and the tenant\u2019s Database Diagnostics page \u2014 together they explain most reported issues."),
    ]},
    {"heading": "Go-Live Checklist", "blocks": [
        ("purpose", "Confirm the platform is ready before onboarding the first paying customer."),
        ("bullets", [
            "Default superadmin password has been rotated to a strong, unique value.",
            "Subscription plans are defined and assigned correctly.",
            "Backups are scheduled and a test restore has been verified.",
            "HTTPS, security headers, and rate limiting are confirmed active.",
            "QA runner passes end-to-end on a staging environment.",
            "Pilot tenant has been provisioned, migrated, routed, and validated.",
            "Rollback (Disable Routing) has been rehearsed and confirmed instant.",
            "Operations team has access to this manual and the internal release guides.",
        ]),
        ("warning", "Do not skip rotating the default superadmin password. This is a mandatory pre-go-live security action."),
    ]},
]

# =====================================================================
# MANUAL 2 — TENANT ADMIN (CUSTOMER FACING)
# =====================================================================

def mod(heading, purpose, steps, fig, cap, expected, extras=None):
    blocks = [("purpose", purpose)]
    if steps:
        blocks.append(("steps", steps))
    if fig:
        blocks.append(("fig", fig, cap))
    if expected:
        blocks.append(("expected", expected))
    if extras:
        blocks.extend(extras)
    return {"heading": heading, "blocks": blocks}


TENANTADMIN = [
    {"heading": "Introduction", "blocks": [
        ("purpose", "This guide helps the store owner or administrator set up and run their Hardware Supply POS account: configuring the business, managing branches and staff, maintaining products and inventory, selling, and reading reports."),
        ("p", "Hardware Supply POS is an online point-of-sale and inventory system built for hardware and construction-supply stores. Your data is private to your business."),
        ("tip", "Work through this manual in order the first time. Setting up Settings, Branches, Categories, Units, and Products first makes selling and reporting accurate from day one."),
    ]},
    mod("Login", "Sign in securely to your account.",
        ["Open your store\u2019s Hardware Supply POS web address.",
         "Enter your username and password.",
         "Click Sign In."],
        "login", "Login screen \u2014 sign in with your username and password.",
        "You are signed in and taken to your Dashboard.",
        [("note", "If you mistype your password several times the account is temporarily locked for security. Wait a few minutes and try again, or ask your administrator to reset it.")]),
    mod("Dashboard", "See the health of your business at a glance.",
        ["Sign in to land on the Dashboard.",
         "Review the summary cards and charts (sales, stock alerts, and key figures).",
         "Use the left menu to open any module."],
        "owner_dashboard", "Tenant Dashboard \u2014 sales, inventory, and business KPIs.",
        "You see live totals for your selected branch and quick access to every module."),
    mod("Settings", "Configure how the system behaves for your business.",
        ["Open Administration \u2192 Settings.",
         "Set your currency, tax mode and VAT percentage, and receipt options.",
         "Save your changes."],
        "owner_settings", "Settings \u2014 business profile, tax, currency, and receipt options.",
        "Your preferences apply across POS, receipts, and reports.",
        [("note", "The VAT percentage you set here is used to calculate tax on the POS and on receipts.")]),
    mod("Business Profile", "Record your business identity for receipts and reports.",
        ["Open Administration \u2192 Settings.",
         "Enter your business name, tax identification number (TIN), and contact details.",
         "Enter the receipt footer message customers will see.",
         "Save."],
        "owner_settings", "Business Profile \u2014 business name, TIN, and receipt footer.",
        "Your business details appear on printed receipts and documents."),
    mod("Logo Upload", "Add your store logo to brand the system and receipts.",
        ["Open Administration \u2192 Settings.",
         "Use the logo upload control to select an image from your computer.",
         "Save. The logo is stored securely for your business only."],
        "owner_settings", "Logo upload \u2014 brand the system with your store logo.",
        "Your logo appears in the application and on documents.",
        [("warning", "Logo files must be 2 MB or smaller. Use a PNG or JPG for best results.")]),
    mod("Branch Management", "Set up and maintain your store branches.",
        ["Open Inventory \u2192 (Branches) or the Branches menu.",
         "Add each branch with its name, code, address, and contact.",
         "Mark your primary location as the Main Branch.",
         "Keep inactive branches deactivated rather than deleting them."],
        "owner_branches", "Branches \u2014 manage all store locations.",
        "Each branch can hold its own stock and process its own sales."),
    mod("User Management", "Create staff accounts and assign them to branches.",
        ["Open Administration \u2192 User Branches (user assignments).",
         "Assign each staff member to the branch(es) they work in.",
         "Confirm each user has the correct role (for example Cashier or Branch Manager)."],
        "owner_userbranches", "User\u2013branch assignments \u2014 control which staff work in which branch.",
        "Staff only see and act on the branches assigned to them.",
        [("tip", "Give each employee their own account. Shared logins make the audit trail and cashier reports unreliable.")]),
    mod("Categories", "Group products for easier management and reporting.",
        ["Open Inventory \u2192 Categories.",
         "Add categories such as Power Tools, Plumbing, Electrical, and Fasteners.",
         "Save."],
        "owner_categories", "Categories \u2014 group products for filtering and reporting.",
        "Categories appear in product filters and inventory reports."),
    mod("Units", "Define the units you sell products in.",
        ["Open Inventory \u2192 Units.",
         "Add units such as Piece, Box, and Meter with short names.",
         "Save."],
        "owner_units", "Units of measure \u2014 piece, box, meter, and more.",
        "Units are selectable when you create products and appear on receipts."),
    mod("Products", "Maintain your product catalog \u2014 codes, prices, and stock levels.",
        ["Open Inventory \u2192 Products.",
         "Click Add Product and enter the code, name, category, unit, and supplier.",
         "Set the cost price, selling price, and reorder level.",
         "Save."],
        "owner_products", "Products \u2014 catalog with codes, pricing, stock, and reorder levels.",
        "Products become available in POS and are tracked in inventory.",
        [("tip", "Set a sensible reorder level for each product so the system can warn you before you run out.")]),
    mod("Inventory", "Monitor stock on hand across your branches.",
        ["Open Inventory \u2192 Inventory.",
         "Review current stock levels and low-stock indicators.",
         "Use search and filters to find specific items."],
        "owner_inventory", "Inventory \u2014 stock on hand and low-stock indicators.",
        "You can see exactly what is in stock and what needs reordering."),
    mod("Suppliers", "Keep records of the vendors you buy from.",
        ["Open Inventory \u2192 Suppliers (or the Suppliers menu).",
         "Add each supplier\u2019s name, contact person, and contact details.",
         "Save."],
        "owner_suppliers", "Suppliers \u2014 vendor records used in purchasing and payables.",
        "Suppliers can be linked to products, purchase orders, and payments."),
    mod("Customers", "Maintain customer records for sales and credit.",
        ["Open Customers \u2192 Customers.",
         "Add customers with their contact details and type (for example Regular or Walk-in).",
         "Save."],
        "owner_customers", "Customers \u2014 records used for sales, credit, and collections.",
        "Customers can be selected at the POS and tracked for balances."),
    mod("Purchase Orders", "Order stock from your suppliers.",
        ["Open Inventory \u2192 Purchase Orders.",
         "Create a new order, choose the supplier, and add the products and quantities.",
         "Save and send the order to your supplier."],
        "owner_purchaseorders", "Purchase Orders \u2014 order stock from suppliers.",
        "Open purchase orders are tracked until the goods are received."),
    mod("Receiving Inventory", "Record stock that arrives from suppliers (Stock In).",
        ["Open Inventory \u2192 Stock In.",
         "Create a Stock In entry, selecting the supplier and (where applicable) the purchase order.",
         "Enter received quantities and costs.",
         "Save to increase stock at the receiving branch."],
        "owner_stockin", "Stock In \u2014 record received goods and update stock.",
        "Stock levels increase and a payable to the supplier is recorded."),
    mod("Stock Adjustments", "Correct stock for damage, loss, or count differences.",
        ["Open Inventory \u2192 Stock Adjustment.",
         "Create an adjustment and choose the branch and items.",
         "Enter the corrected quantity and a reason.",
         "Save."],
        "owner_stockadjustment", "Stock Adjustment \u2014 correct stock with a reason for the change.",
        "Stock is corrected and the change is recorded for audit.",
        [("warning", "Always enter a clear reason for every adjustment. Adjustments change your stock value and are reviewed in reports.")]),
    mod("Branch Transfers", "Move stock between your branches.",
        ["Open Inventory \u2192 Branch Transfers.",
         "Create a transfer from the source branch to the destination branch.",
         "Add the items and quantities.",
         "Save and complete the transfer when goods arrive."],
        "owner_branchtransfers", "Branch Transfers \u2014 move stock between locations.",
        "Stock decreases at the source and increases at the destination branch."),
    mod("Quotations", "Give customers a price quote before a sale.",
        ["Open Operations \u2192 Quotations.",
         "Create a quotation, choose the customer, and add items and prices.",
         "Save and share the quotation with the customer."],
        "owner_quotations", "Quotations \u2014 prepare price quotes for customers.",
        "Quotations can be referenced when the customer decides to buy."),
    mod("Delivery Receipts", "Document goods delivered to customers.",
        ["Open Operations \u2192 Delivery Receipts.",
         "Create a delivery receipt for the customer and items delivered.",
         "Save and print for the customer to sign."],
        "owner_deliveryreceipts", "Delivery Receipts \u2014 record goods delivered to customers.",
        "You have a signed record of what was delivered and when."),
    mod("POS Sales", "Sell products quickly at the point of sale.",
        ["Open Operations \u2192 POS.",
         "Search for an item and add it to the order; adjust quantities as needed.",
         "Choose the customer (or Walk-in), apply any discount, and select the payment method.",
         "Enter the amount received and complete the sale."],
        "owner_pos", "Point of Sale \u2014 add items, take payment, and complete a sale.",
        "The sale is recorded, stock is reduced, and a receipt is produced."),
    mod("Credit Sales", "Sell on account to trusted customers.",
        ["At the POS, select a registered customer (not Walk-in).",
         "Add items as usual.",
         "Choose the credit/charge payment option for the unpaid balance.",
         "Complete the sale; the balance is added to the customer\u2019s account."],
        "owner_pos", "Credit sale \u2014 select a customer and charge the balance to their account.",
        "The unpaid balance is tracked against the customer for later collection.",
        [("warning", "Only extend credit to customers you trust. Monitor outstanding balances using the Aging Receivables report.")]),
    mod("Customer Collections", "Receive payments against customer balances.",
        ["Open Operations \u2192 Collections.",
         "Select the customer and the outstanding amount.",
         "Record the payment received.",
         "Save."],
        "owner_collections", "Collections \u2014 record payments against customer balances.",
        "The customer\u2019s outstanding balance is reduced and the payment is recorded."),
    mod("Supplier Payments", "Pay your suppliers for received goods.",
        ["Open Reports \u2192 Supplier Payables to review what you owe per stock-in invoice.",
         "From a payable, open Pay and record the amount paid.",
         "Save to reduce the outstanding balance to that supplier."],
        "owner_supplierpayments", "Supplier Payables \u2014 track and settle what you owe suppliers.",
        "The amount owed to the supplier is reduced and the payment is recorded.",
        [("note", "Supplier payments are made against received Stock In invoices, so receive your goods first, then pay.")]),
    mod("Expenses", "Track operating costs such as utilities and rent.",
        ["Open Operations \u2192 Expenses.",
         "Add an expense with its category, amount, and date.",
         "Save."],
        "owner_expenses", "Expenses \u2014 record operating costs by category.",
        "Expenses are included in profit reporting (Expense vs Profit)."),
    mod("Reports", "Make decisions using sales, inventory, and financial reports.",
        ["Open the Reports menu.",
         "Choose a report (for example Sales Detail, Profitability, or Aging Receivables).",
         "Set the date range and filters, then view or export.",
         "Use Export (PDF/Excel) to save or share a report."],
        "owner_reports", "Reports \u2014 sales, inventory, customer, supplier, and financial reporting.",
        "You can analyze performance and export reports for sharing."),
    mod("Inventory Intelligence", "Use advanced stock analytics to optimize purchasing.",
        ["Open Reports and select an inventory-intelligence report.",
         "Review Fast / Slow Moving items to guide purchasing.",
         "Open Inventory Valuation to see the value of stock on hand.",
         "Use ABC analysis, dead-stock, and reorder suggestions to refine stock."],
        "owner_inv_intel", "Fast / Slow Moving items \u2014 identify which products to reorder or discount.",
        "You can prioritize fast movers and act on slow or dead stock.",
        [("fig", "owner_inv_valuation", "Inventory Valuation \u2014 the current value of stock on hand."),
         ("tip", "Review Fast/Slow Moving and Reorder Suggestions weekly to keep cash tied up in the right stock.")]),
    mod("Imports", "Bring existing data into the system from spreadsheets.",
        ["Open Inventory \u2192 Excel Import (Imports).",
         "Download the template, fill it with your data, and upload the file.",
         "Map the columns, preview the rows, and confirm the import.",
         "Review the result summary for any rows that need attention."],
        "owner_import", "Imports \u2014 load products and data from Excel with column mapping and preview.",
        "Valid rows are imported; problem rows are reported so you can correct and re-import.",
        [("tip", "Always use the preview step to catch formatting issues before committing an import.")]),
    mod("Audit Logs", "See who changed what in your account.",
        ["Open Administration \u2192 Audit Trail.",
         "Filter by user, action, module, or date.",
         "Open an entry for details."],
        "owner_audit", "Audit Logs \u2014 a record of actions taken in your account.",
        "You can review and investigate changes made by your staff."),
    {"heading": "Best Practices", "blocks": [
        ("purpose", "Get the most from Hardware Supply POS and keep your data accurate."),
        ("bullets", [
            "Give every employee their own account and the minimum role they need.",
            "Set reorder levels on products so low-stock warnings are meaningful.",
            "Receive stock (Stock In) promptly so inventory and payables stay accurate.",
            "Record expenses as they happen for reliable profit reporting.",
            "Reconcile customer and supplier balances regularly using the aging reports.",
            "Review the audit trail if numbers ever look unexpected.",
        ]),
        ("tip", "A few minutes of daily housekeeping (receiving stock, recording expenses, taking collections) keeps every report trustworthy."),
    ]},
    {"heading": "FAQ", "blocks": [
        ("purpose", "Answers to the questions store owners ask most often."),
        ("h2", "I forgot my password \u2014 what do I do?"),
        ("p", "Ask your administrator to reset it, or contact support. For security, accounts lock briefly after several failed attempts."),
        ("h2", "Why can a cashier not see a menu?"),
        ("p", "Menus follow roles. Cashiers see only what their role allows. Ask your administrator to adjust the role\u2019s permissions if needed."),
        ("h2", "Why is stock different between branches?"),
        ("p", "Stock is tracked per branch. Use Branch Transfers to move stock, and Stock Adjustments to correct counts."),
        ("h2", "Can I sell on credit?"),
        ("p", "Yes. Select a registered customer at the POS and charge the balance to their account, then collect later under Collections."),
        ("h2", "How do I get my data out?"),
        ("p", "Most reports offer Export to PDF or Excel. Use these to share figures with your accountant."),
    ]},
]

# =====================================================================
# MANUAL 3 — CASHIER QUICK GUIDE
# =====================================================================
CASHIER = [
    mod("Login", "Sign in to start your shift.",
        ["Open Hardware Supply POS in your browser.",
         "Enter your username and password.",
         "Click Sign In."],
        "login", "Login screen \u2014 enter your username and password.",
        "You are signed in and ready to select your branch.",
        [("note", "Use your own account. Never share your password.")]),
    mod("Select Branch", "Choose the branch you are working in.",
        ["After signing in, find the branch selector at the top of the screen.",
         "Choose your branch from the list.",
         "The system now uses that branch\u2019s stock and prices."],
        "cashier_branch", "Branch selector \u2014 choose the location you are working in.",
        "Your sales and stock will apply to the selected branch."),
    mod("Create Sale", "Ring up items for a customer.",
        ["Open Operations \u2192 POS.",
         "Search for an item by name, code, or barcode.",
         "Click the add (+) button to put it in the order; repeat for each item.",
         "Adjust quantities in the Order Summary as needed."],
        "cashier_pos", "POS screen \u2014 search items and build the order.",
        "All items appear in the Order Summary with a running total."),
    mod("Add Customer", "Attach a customer to the sale (optional).",
        ["In the Customer box on the POS, choose a registered customer, or leave it as Walk-in.",
         "For a credit sale, you must select a registered customer."],
        "cashier_pos", "Customer selection on the POS \u2014 Walk-in or a registered customer.",
        "The chosen customer is linked to the sale and the receipt."),
    mod("Receive Payment", "Take the customer\u2019s payment and give change.",
        ["Confirm the total in the Order Summary.",
         "Apply a discount only if you are authorized to.",
         "Choose the payment method (for example Cash).",
         "Enter the Amount Received \u2014 the system calculates the change.",
         "Complete the sale."],
        "cashier_pos", "Payment area \u2014 method, amount received, and change.",
        "The sale is saved, stock is reduced, and a receipt is ready to print.",
        [("warning", "Count the cash and the change carefully before finishing the sale.")]),
    mod("Print Receipt", "Give the customer their receipt.",
        ["After completing the sale, the receipt is shown on screen.",
         "Click Print Receipt.",
         "Hand the printed receipt to the customer."],
        "cashier_receipt", "Receipt screen \u2014 review and print the customer\u2019s receipt.",
        "The customer receives a printed receipt with your store\u2019s details."),
    mod("View Sale History", "Look up sales you have processed.",
        ["Open Operations \u2192 Sales.",
         "Use search and date filters to find a sale.",
         "Open a sale to view details or reprint its receipt."],
        "cashier_saleshistory", "Sales history \u2014 find and review past sales.",
        "You can locate any past sale and reprint its receipt."),
    {"heading": "Logout", "blocks": [
        ("purpose", "Protect the till when you step away or end your shift."),
        ("steps", [
            "Click your name in the top-right corner.",
            "Choose Logout.",
            "Confirm you are returned to the sign-in screen.",
        ]),
        ("warning", "Always log out at the end of your shift so no one can sell under your account."),
    ]},
    {"heading": "Common Errors", "blocks": [
        ("purpose", "Quick fixes for everyday problems."),
        ("bullets", [
            "\u201cItem out of stock\u201d \u2014 the item has no stock at your branch. Ask a supervisor to transfer or receive stock.",
            "Cannot find an item \u2014 try the code or barcode instead of the name; check spelling.",
            "Wrong branch \u2014 use the branch selector at the top to switch to your correct branch.",
            "Cannot apply a discount \u2014 you may not be authorized. Ask a supervisor.",
            "Locked out after wrong passwords \u2014 wait a few minutes, then sign in again.",
        ]),
    ]},
    {"heading": "Quick Tips", "blocks": [
        ("purpose", "Be faster and more accurate at the till."),
        ("bullets", [
            "Scan or type the barcode to add items instantly.",
            "Confirm the customer\u2019s name for credit sales before completing.",
            "Re-read the total and change amount out loud to the customer.",
            "Reprint a receipt any time from Sales history.",
            "Log out whenever you leave the counter.",
        ]),
        ("tip", "Keep the Order Summary visible while ringing up \u2014 it shows the live total, discount, VAT, and change."),
    ]},
]


def main():
    jobs = [
        (Manual("SuperAdmin Manual", "Platform Administration & Operations Guide",
                "System Owner / Platform Operator", "Internal \u2013 Confidential"),
         SUPERADMIN, "SuperAdminManual.docx"),
        (Manual("Tenant Admin Manual", "Store Owner & Administrator Guide",
                "Store Owner / Tenant Administrator", "Customer Documentation"),
         TENANTADMIN, "TenantAdminManual.docx"),
        (Manual("Cashier Quick Guide", "Point-of-Sale Quick Reference",
                "Cashiers / Sales Clerks", "Customer Documentation"),
         CASHIER, "CashierQuickGuide.docx"),
    ]
    for manual, sections, fname in jobs:
        out = os.path.join(OUT, fname)
        manual.build(sections, out)
        print(f"[DOCX] {fname}: {len(sections)} sections, {manual.fig} figures -> {out}")


if __name__ == "__main__":
    main()
